"""Train the forecasting bundle and measure it with a rolling-origin backtest.

    python -m src.train                 # backtest + fit + write pickle/model.pkl and docs/
    python -m src.train --skip-backtest # refit only, reuse the calibration in the existing bundle

Order of operations:
1. Rolling-origin backtest: refit on truncated data at every weekly origin and
   forecast the 30/60/90 days that followed (src/backtest.py).
2. Conformal calibration of the intervals from those out-of-sample residuals.
3. Final fit on all data, bundled with the calibration and a seasonal reference.
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import numpy as np
import pandas as pd

from src.backtest import (
    compare_with_legacy,
    honest_forecasts,
    run_backtest,
    summarise,
    test_origins,
    training_origins,
)
from src.config import HORIZONS, INTERVAL_COVERAGE, META_CONVERSION_AS_REVENUE, RANDOM_SEED, ROOT
from src.features import SeasonalReference, build_samples
from src.forecast import public_columns
from src.model import fit_conformal, fit_core, load_bundle, make_bundle, save_bundle
from src.pipeline import prepare_data

DOCS = ROOT / "docs"
LEGACY_BACKTEST = DOCS / "legacy_v31_backtest.csv"


def _records(df: pd.DataFrame) -> list[dict]:
    return json.loads(df.round(4).to_json(orient="records", date_format="iso"))


def backtest_report(fc: pd.DataFrame) -> dict:
    """Summary tables stored in the bundle and written to docs/."""
    by_level = summarise(fc)
    by_season = summarise(fc, by=["peak"])
    report = {
        "protocol": "rolling-origin, refit at every origin on data truncated at that origin",
        "n_origins": int(fc["origin"].nunique()),
        "first_origin": str(fc["origin"].min().date()),
        "last_origin": str(fc["origin"].max().date()),
        "interval": f"P{int((1 - INTERVAL_COVERAGE) / 2 * 100)}-P{int((1 + INTERVAL_COVERAGE) / 2 * 100)}",
        "by_level": _records(by_level),
        "by_season": _records(by_season),
    }
    if LEGACY_BACKTEST.exists():
        report["vs_v31"] = _records(compare_with_legacy(fc, pd.read_csv(LEGACY_BACKTEST)))
    # per-origin top-of-hierarchy forecasts for the dashboard's backtest replay
    top = fc[fc["level"].isin(["blended", "channel"])]
    cols = ["origin", "level", "channel", "horizon_days", "revenue_p10", "revenue_p50", "revenue_p90",
            "budget_revenue_p50", "baseline_revenue", "actual_revenue", "spend_p50", "actual_spend", "peak"]
    report["replay"] = _records(top[cols])
    return report


def write_docs(fc: pd.DataFrame, report: dict) -> None:
    DOCS.mkdir(exist_ok=True)
    pd.DataFrame(report["by_level"]).to_csv(DOCS / "backtest_by_level.csv", index=False)
    pd.DataFrame(report["by_season"]).to_csv(DOCS / "backtest_by_season.csv", index=False)
    if "vs_v31" in report:
        pd.DataFrame(report["vs_v31"]).to_csv(DOCS / "backtest_vs_v31.csv", index=False)
    keep = public_columns(fc[fc["level"] != "campaign"])
    keep.to_csv(DOCS / "backtest_forecasts.csv", index=False)
    with open(DOCS / "validation_results.json", "w", encoding="utf-8") as f:
        json.dump({k: v for k, v in report.items() if k != "replay"}, f, indent=2)
    (DOCS / "results.md").write_text(results_markdown(report), encoding="utf-8")


_LEVEL_NAMES = {"blended": "Blended", "channel": "Channel", "campaign_type": "Campaign type", "campaign": "Campaign"}


def _md_table(df: pd.DataFrame, columns: dict[str, str], fmt: dict[str, str]) -> str:
    """Markdown table of selected columns ({source: header}) with per-column formats."""
    head = "| " + " | ".join(columns.values()) + " |"
    rule = "|" + "|".join("---" if c in ("level", "season") else "---:" for c in columns) + "|"
    rows = []
    for _, r in df.iterrows():
        cells = []
        for c in columns:
            v = r[c]
            cells.append(_LEVEL_NAMES.get(v, str(v)) if isinstance(v, str)
                         else "-" if pd.isna(v) else fmt.get(c, "{:.1f}").format(v))
        rows.append("| " + " | ".join(cells) + " |")
    return "\n".join([head, rule, *rows])


def _bias_range(by_season: pd.DataFrame, peak: bool) -> str:
    b = by_season[(by_season["peak"] == peak) & (by_season["level"] == "blended")]["bias_pct"]
    return f"{b.min():+.0f}% to {b.max():+.0f}%" if len(b) else "n/a"


def _wape_range(by_season: pd.DataFrame, peak: bool, col: str) -> str:
    b = by_season[(by_season["peak"] == peak) & (by_season["level"] == "blended")][col]
    return f"{b.min():.0f}-{b.max():.0f}%" if len(b) else "n/a"


def results_markdown(report: dict) -> str:
    """docs/results.md, regenerated by every training run so it always matches the shipped model."""
    by_level = pd.DataFrame(report["by_level"])
    by_season = pd.DataFrame(report["by_season"])
    by_season["season"] = np.where(by_season["peak"], "Touches peak season", "Rest of year")
    blended = by_level[by_level["level"] == "blended"].set_index("horizon_days")
    pct, cnt = "{:.1f}%", "{:.0f}"
    acc_cols = {"level": "Level", "horizon_days": "Horizon (days)", "n": "Forecasts", "wape": "WAPE",
                "wape_budget_known": "WAPE, budget known", "wape_run_rate": "Run-rate baseline",
                "wape_seasonal_naive": "Seasonal-naive baseline", "bias_pct": "Bias"}
    acc_fmt = {"horizon_days": cnt, "n": cnt, "wape": pct, "wape_budget_known": pct, "wape_run_rate": pct,
               "wape_seasonal_naive": pct, "bias_pct": "{:+.1f}%"}
    cal_cols = {"level": "Level", "horizon_days": "Horizon (days)", "n_coverage": "Forecasts scored",
                "coverage": "Revenue P10-P90 coverage", "coverage_budget_known": "…with budget known",
                "roas_coverage": "ROAS P10-P90 coverage", "interval_width_pct": "Range width / actual",
                "pinball_pct": "Pinball loss / actual", "spend_wape": "Spend WAPE", "roas_wape": "ROAS error"}
    cal_fmt = {"horizon_days": cnt, "n_coverage": cnt, "coverage": pct, "coverage_budget_known": pct,
               "roas_coverage": pct, "interval_width_pct": pct, "pinball_pct": pct, "spend_wape": pct,
               "roas_wape": pct}

    parts = [
        "# Backtest results",
        "",
        "_Generated by `python -m src.train`. Do not edit by hand: re-train to refresh._",
        "",
        f"**Protocol.** {report['n_origins']} weekly forecast origins from {report['first_origin']} to "
        f"{report['last_origin']}. At each origin the data is truncated at that date, the whole model is refitted "
        "on what was visible then, and the revenue of the following 30 / 60 / 90 days is forecast for every node "
        "of the hierarchy and compared with what happened. Interval calibration at an origin uses only residuals "
        "from earlier origins whose windows had already closed. Nothing is filtered out: zero-revenue rows, "
        "dormant campaigns and peak season are all scored.",
        "",
        "**Metrics.** WAPE = sum of absolute errors / sum of actual revenue (lower is better). "
        "Coverage = share of actuals inside the P10-P90 range (target 80%). "
        "Bias = total forecast / total actual - 1. "
        "ROAS error = revenue error if the realised spend is multiplied by the forecast ROAS.",
        "",
        "## Headline",
        "",
        "| Horizon | Blended WAPE | Run-rate baseline | Seasonal-naive baseline | WAPE with budget known | P10-P90 coverage |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    for h in sorted(blended.index):
        b = blended.loc[h]
        parts.append(f"| {int(h)} days | **{b['wape']:.1f}%** | {b['wape_run_rate']:.1f}% | "
                     f"{b['wape_seasonal_naive']:.1f}% | **{b['wape_budget_known']:.1f}%** | {b['coverage']:.0f}% |")
    parts += [
        "",
        "\"Budget known\" re-runs the same forecasts with the spend that was actually deployed, through the "
        "fitted elasticity. It is what the Budget simulator delivers when the analyst enters the real plan, and "
        "it shows how much of the blind error is simply not knowing the budget.",
        "",
    ]
    if "vs_v31" in report:
        legacy = pd.DataFrame(report["vs_v31"])
        parts += [
            "## Against the previous pipeline (v3.1)",
            "",
            "The v3.1 pipeline was put through the same protocol: retrained at each origin exactly as its "
            "`train.py` did, then asked for the forecast its `run.sh` would have written. The comparison covers "
            f"the {int(legacy['origins'].max())} origins and the series both pipelines produced "
            "(v3.1 emitted only its top 20 campaigns).",
            "",
            _md_table(legacy, {"level": "Level", "horizon_days": "Horizon (days)", "n": "Forecasts",
                               "wape_v31": "WAPE v3.1", "wape_v4": "WAPE v4", "coverage_v31": "Coverage v3.1",
                               "coverage_v4": "Coverage v4", "bias_pct_v31": "Bias v3.1", "bias_pct_v4": "Bias v4"},
                      {"horizon_days": cnt, "n": cnt, "wape_v31": pct, "wape_v4": pct, "coverage_v31": "{:.0f}%",
                       "coverage_v4": "{:.0f}%", "bias_pct_v31": "{:+.0f}%", "bias_pct_v4": "{:+.0f}%"}),
            "",
            "v3.1's published 35.8% WAPE came from a different measurement: one-step weekly rows, the realised "
            "future spend supplied as a feature, rows under $500 filtered out, and training targets that "
            "overlapped the holdout. Under forward-looking scoring it under-forecast by roughly half.",
            "",
        ]
    parts += [
        "## Accuracy by level",
        "",
        _md_table(by_level, acc_cols, acc_fmt),
        "",
        "## Calibration, spend and ROAS",
        "",
        _md_table(by_level, cal_cols, cal_fmt),
        "",
        "Coverage is scored only on origins that had at least eight earlier, fully elapsed origins to calibrate "
        "from, which is why fewer forecasts are scored at the longer horizons.",
        "",
        "## Peak season vs the rest of the year",
        "",
        "A forecast \"touches peak season\" when its target window or its 28-day base window overlaps "
        "18 Nov - 24 Dec.",
        "",
        _md_table(by_season[by_season["level"].isin(["blended", "channel", "campaign_type"])],
                  {"season": "Season", **acc_cols}, acc_fmt),
        "",
        "## Reading these numbers",
        "",
        "- Two kinds of event dominate the error, and they differ. The size and timing of the November-December "
        "peak is a budget decision: when the window touches peak season, knowing the budget cuts blended WAPE "
        "from " + _wape_range(by_season, True, "wape") + " to " + _wape_range(by_season, True, "wape_budget_known")
        + ". The end of a promotion (May-June 2025) is a collapse in revenue per dollar, which a budget plan "
        "does not fix; it is the reason the P10 sits far below the median.",
        "- Campaign-level forecasts are directional. Individual campaigns start, stop and spike; plan budgets at "
        "channel or campaign-type level.",
        "- Blended bias is " + _bias_range(by_season, True) + " when the window touches peak season (2025's peak "
        "outgrew its 2024 analog) and " + _bias_range(by_season, False) + " in the rest of the year.",
        "- Files: `backtest_by_level.csv`, `backtest_by_season.csv`, `backtest_vs_v31.csv`, "
        "`backtest_forecasts.csv` (every non-campaign forecast with its actual), `validation_results.json`.",
        "",
    ]
    return "\n".join(parts)


def print_summary(report: dict) -> None:
    table = pd.DataFrame(report["by_level"])
    cols = ["level", "horizon_days", "n", "wape", "wape_budget_known", "wape_run_rate",
            "wape_seasonal_naive", "coverage", "roas_wape", "roas_coverage"]
    print()
    print("=" * 100)
    print(f"  Rolling-origin backtest: {report['n_origins']} weekly origins, "
          f"{report['first_origin']} to {report['last_origin']}")
    print("=" * 100)
    print(table[cols].round(1).to_string(index=False))
    if "vs_v31" in report:
        print("\n  Same origins and series as the v3.1 pipeline:")
        print(pd.DataFrame(report["vs_v31"]).round(1).to_string(index=False))
    print("=" * 100)


def main() -> None:
    parser = argparse.ArgumentParser(description="Train the AIgnition forecasting bundle")
    parser.add_argument("--data-dir", default=str(ROOT / "data"))
    parser.add_argument("--model-path", default=str(ROOT / "pickle" / "model.pkl"))
    parser.add_argument("--skip-backtest", action="store_true",
                        help="Refit only; keep the calibration and backtest of the existing bundle")
    args = parser.parse_args()
    np.random.seed(RANDOM_SEED)

    t0 = time.time()
    prepared = prepare_data(args.data_dir)
    hier = prepared.hier
    print(f"[data] {hier.dates[0].date()} to {hier.origin.date()} | {hier.n_series} series | "
          f"{len(prepared.cleaned):,} daily rows")

    if args.skip_backtest:
        previous = load_bundle(args.model_path)
        conformal, report = previous["conformal"], previous.get("backtest", {})
    else:
        origins = test_origins(hier)
        if len(origins) < 12:
            raise SystemExit("Not enough history for a rolling-origin backtest "
                             "(need roughly 20 months). Use --skip-backtest with an existing bundle.")
        oos = run_backtest(hier, origins)
        conformal = fit_conformal(oos)
        fc = honest_forecasts(oos)
        report = backtest_report(fc)
        write_docs(fc, report)
        print_summary(report)

    samples = build_samples(hier, training_origins(hier.n_days - 1))
    core = fit_core(samples)
    bundle = make_bundle(
        core, conformal,
        seasonal_reference=SeasonalReference.from_hierarchy(hier).to_dict(),
        trained_on={
            "first_date": str(hier.dates[0].date()),
            "last_date": str(hier.origin.date()),
            "n_series": int(hier.n_series),
            "n_samples": int(core["n_samples"]),
            "horizons": list(HORIZONS),
            "meta_revenue_assumption": "conversion_as_revenue" if META_CONVERSION_AS_REVENUE else "meta_excluded",
            "validation": prepared.report.to_dict(),
        },
        backtest=report,
    )
    save_bundle(bundle, args.model_path)
    size_kb = Path(args.model_path).stat().st_size / 1024
    print(f"[model] {core['n_samples']:,} training rows -> {args.model_path} ({size_kb:,.0f} KB) "
          f"in {time.time() - t0:.0f}s")
    for h in HORIZONS:
        top = core["linear"]["rev"][h].get("top", core["linear"]["rev"][h]["all"])
        print(f"[model] {h}d  spend elasticity {core['elasticity'][h]['base']:.2f}  |  top-level weights: "
              f"peak-season analog {top['seas_peak']:.2f}, off-season analog {top['seas_off']:.2f}, "
              f"7-day momentum {top['mom_r7']:.2f} (revenue) {top['mom_s7']:.2f} (spend)")


if __name__ == "__main__":
    main()
